// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grtkmwuupfhmhurhqzcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydGttd3V1cGZobWh1cmhxemNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDIwMjcsImV4cCI6MjA2NzkxODAyN30.EdCwuD4iYwIi-Ao6RLYy7mUkRqCbF8wRbwqT641T6-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});